export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      backgroundImage: {
        'primary-gradient': 'linear-gradient(135deg, #595e6f 0%, #4d5263 100%)',
      },
      colors: {
        "surface-container": "#eaeff1",
        "on-secondary-container": "#515155",
        "primary-dim": "#4d5263",
        "on-primary-container": "#4c5162",
        "inverse-primary": "#dbdff4",
        "secondary-container": "#e4e2e6",
        "primary": "#595e6f",
        "secondary-fixed": "#e4e2e6",
        "secondary": "#5f5f62",
        "secondary-dim": "#535356",
        "surface-dim": "#d1dce0",
        "surface-tint": "#595e6f",
        "error": "#9f403d",
        "tertiary-fixed": "#e1d8fa",
        "outline-variant": "#abb3b7",
        "primary-fixed": "#dee2f7",
        "tertiary-container": "#e1d8fa",
        "inverse-on-surface": "#9b9d9e",
        "on-secondary-fixed": "#3f3f43",
        "surface-container-highest": "#dbe4e7",
        "error-dim": "#4e0309",
        "on-error-container": "#752121",
        "inverse-surface": "#0c0f10",
        "tertiary": "#615b77",
        "on-tertiary-container": "#504b66",
        "on-secondary-fixed-variant": "#5b5b5f",
        "on-primary-fixed-variant": "#565b6c",
        "on-error": "#fff7f6",
        "on-secondary": "#faf8fc",
        "on-primary": "#f8f7ff",
        "tertiary-fixed-dim": "#d3caeb",
        "on-surface": "#2b3437",
        "on-primary-fixed": "#3a3f4f",
        "background": "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "secondary-fixed-dim": "#d5d4d8",
        "surface-container-low": "#f1f4f6",
        "on-background": "#2b3437",
        "tertiary-dim": "#554f6b",
        "surface-variant": "#dbe4e7",
        "on-tertiary-fixed-variant": "#5a5470",
        "surface-container-high": "#e2e9ec",
        "outline": "#737c7f",
        "on-surface-variant": "#586064",
        "error-container": "#fe8983",
        "on-tertiary": "#fcf7ff",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#dee2f7",
        "on-primary-container": "#4c5162",
      },
      fontFamily: {
        'Be_Vietnam_Pro': ['Be Vietnam Pro', 'sans-serif'],
        'Inter': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
